package com.eshore.university.module.dao;

import com.eshore.university.module.pojo.TAdmin;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITAdminDAO extends IBaseDao<TAdmin> {

}