package com.eshore.university.module.dao;

import java.util.List;

import com.eshore.university.module.pojo.TAdmin;
import com.eshore.khala.common.model.PageConfig;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITAdminDAO extends IBaseDao<TAdmin> {

	/***
	 * 根据管理员的属性查找与传入对象属性相同高的管理员
	 * @param t 管理员对象
	 * @return
	 */
	public List<TAdmin> getAdminsByProperty(TAdmin t);
}