package com.eshore.university.module.dao;

import com.eshore.university.module.pojo.TChange;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITChangeDAO extends IBaseDao<TChange> {

}