package com.eshore.university.module.dao;

import com.eshore.university.module.pojo.TClass;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITClassDAO extends IBaseDao<TClass> {

}