package com.eshore.university.module.dao;

import java.util.List;

import com.eshore.university.module.pojo.TClass;
import com.eshore.university.module.pojo.TClassInfo;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITClassDAO extends IBaseDao<TClass> {
	
	/**
	 * 查询出所有状态为上架的课程的信息
	 * @return
	 */
	public List<TClassInfo> findAll();
}