package com.eshore.university.module.dao;

import com.eshore.university.module.pojo.TCourse;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITCourseDAO extends IBaseDao<TCourse> {

}