package com.eshore.university.module.dao;

import com.eshore.university.module.pojo.TNotice;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITNoticeDAO extends IBaseDao<TNotice> {

}