package com.eshore.university.module.dao;

import com.eshore.university.module.pojo.TOld;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITOldDAO extends IBaseDao<TOld> {

}