package com.eshore.university.module.dao;

import com.eshore.university.module.pojo.TRegist;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITRegistDAO extends IBaseDao<TRegist> {

}