package com.eshore.university.module.dao;

import com.eshore.university.module.pojo.TReturn;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITReturnDAO extends IBaseDao<TReturn> {

}