package com.eshore.university.module.dao;

import com.eshore.university.module.pojo.TRoom;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITRoomDAO extends IBaseDao<TRoom> {

}