package com.eshore.university.module.dao;

import java.util.List;

import com.eshore.university.module.pojo.TStaff;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITStaffDAO extends IBaseDao<TStaff> {

	/***
	 * 获取状态为state的教师
	 * @return
	 */
	public List<TStaff> getStaffState(String state);
}