package com.eshore.university.module.dao;

import com.eshore.university.module.pojo.TStaff;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITStaffDAO extends IBaseDao<TStaff> {

}