package com.eshore.university.module.dao;

import com.eshore.university.module.pojo.TTerm;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITTermDAO extends IBaseDao<TTerm> {

}