package com.eshore.university.module.dao;

import com.eshore.university.module.pojo.TTime;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITTimeDAO extends IBaseDao<TTime> {

}