package com.eshore.university.module.dao;

import java.util.List;

import com.eshore.university.module.pojo.TTime;
import com.eshore.khala.core.data.api.dao.IBaseDao;
/**
*generated by tools 
*
*/
public interface ITTimeDAO extends IBaseDao<TTime> {

	/**
	 * 返回符合除传入时间id以外的时间
	 * @return
	 */
	public List<TTime> getTime(int timeid);
}